### ISSUE TITLE
有没有python3 的开发计划？

### ISSUE THREAD

**Issue by Wall-ee** [aliyun/aliyun-tablestore-python-sdk#19]
我们急需python3的支持，目前来说，已通过2to3.py  更改了一些。 但是还是有很多地方的  unicode和str的问题。你们有没有开发计划？或者说 beta版本，我们可以一同来完成

**Comment by qiyuewuyi** [comment]
你们用的是python 3.几？

**Comment by Wall-ee** [comment]
3.4以上都ok,因为我们有太多的cuda和numpy的mkl模块集成开发，降到2.7 实在是开发灾难~~~~哪怕你们是beta版本，我们一起来完成填坑都行~

**Comment by qiyuewuyi** [comment]
由于资源紧张，目前只有一个完成部分改造的分支：https://github.com/aliyun/aliyun-tablestore-python-sdk/tree/python3。

你们可以根据这个改造，有啥问题直接联系我一起解决。
有改动可以提PR。

**Comment by aohan237** [comment]
现在还没有支持3.x真是灾难

**Comment by Wall-ee** [comment]
没事 我提交了一个pr  你可以看下 我在3.4,3.5都测试过了

**Comment by rockuw** [comment]
+1 for Python3.6
