### ISSUE TITLE
Filter挺有用的，希望能添加

### ISSUE THREAD

**Issue by xsh6528** [aliyun/aliyun-tablestore-python-sdk#5]
在我的业务里，用户取消了某个操作。
我不会删除记录行，而是用一个属性is_delete标记为True。（这样方便我保留更多用户隐形喜好，做大数据分析）
因此我很希望SDK能够提供Filter功能，在我查询的时候，提前过滤掉表记为删除的条目。
（我知道这样还是会费读单元）

**Comment by red-chen** [comment]
https://github.com/aliyun/aliyun-tablestore-python-sdk/tree/feature-filter

Filter功能已经提交上来了，你可以试试

**Comment by red-chen** [comment]
已添加condition update和filter功能
