### ISSUE TITLE
4个主键不提供完整时，getRange查询会报错

### ISSUE THREAD

**Issue by xsh6528** [aliyun/aliyun-tablestore-python-sdk#6]
我提供的话，也是提供InfMin, InfMax，来不约束其他主键。
为什么不是SDK底层自动给我补上呢？

**Comment by zhouzf05** [comment]
主要原因是SDK层没有保存表的meta信息，所以不知道主键有多少列，表的meta只保存在服务器端。

如果SDK层要拿meta信息的话，需要增加一次读，还需要处理meta刷新，meta不一致等等问题。

所以实现复杂度是一方面的困难。

另一方面困难是语义的问题，有些场景下是需要MIN到MAX，有些场景下也可以是MAX到MIN。从理解上，用户自己填能更清楚的知道自己选择的范围。
