### ISSUE TITLE
a little confused on function def is_repeatable_api(cls, api_name)

### ISSUE THREAD

**Issue by tobyzxj** [aliyun/aliyun-tablestore-python-sdk#9]
I'm trying to review this python code, then i will port it to  [goots](https://github.com/GiterLab/goots)  project.

In retry.py file, I'm a little confused on function def is_repeatable_api(cls, api_name).

    @classmethod
    def is_repeatable_api(cls, api_name):
        if (api_name == "/ListTable" or
            api_name == "/DescribeTable" or
            api_name == "/GetRow" or
            api_name == "/BatchGetRow" or
            api_name == "/GetRange" or
            api_name == "/DescrieStream" or
            api_name == "/GetShardIterator" or
            api_name == "/GetStreamRecord" or
            api_name == "/ListStream"):
            return True

        return False

 In this function, api_name should like `ListTable`/`DescribeTable`/`GetRow`/`BatchGetRow`/`GetRange`/`DescrieStream`/`GetShardIterator`/`GetStreamRecord`/`ListStream`, there should be no `/`. Isn't it ?

And, i didn't see the API method implementation, which is `DescrieStream`/`GetShardIterator`/`GetStreamRecord`/`ListStream`. Should it be remove, or will be implemented in the future ?

I think this function should be like this:

    @classmethod
    def is_repeatable_api(cls, api_name):
        if (api_name == "ListTable" or
            api_name == "DescribeTable" or
            api_name == "GetRow" or
            api_name == "BatchGetRow" or
            api_name == "GetRange"):
            return True

        return False

**Comment by zhouzf05** [comment]
Thanks for your issue. For your questions:
1. yes, there should be no '/' as prefix, it's a bug and we will fix it soon.
2. 'DescribeStream' and other api will be published in the future, but it's better to remove it before it is published.
